name: Reusable workflow

on:
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        required: true
        default: "Some default value"
        description: "The person to greet"
    outputs:
      current-time:
        description: "Current time output"
        value: ${{ jobs.reusable-job.outputs.current-time }}
      
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello {{ inputs.who-to-greet }}"

      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT

    outputs:
      current-time: ${{ steps.time.outputs.time }}
        
